program Project1;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  Horse.Callback in 'Vendor\Horse\Horse.Callback.pas',
  Horse.Commons in 'Vendor\Horse\Horse.Commons.pas',
  Horse.Constants in 'Vendor\Horse\Horse.Constants.pas',
  Horse.Core.Files in 'Vendor\Horse\Horse.Core.Files.pas',
  Horse.Core.Group.Contract in 'Vendor\Horse\Horse.Core.Group.Contract.pas',
  Horse.Core.Group in 'Vendor\Horse\Horse.Core.Group.pas',
  Horse.Core.Param.Config in 'Vendor\Horse\Horse.Core.Param.Config.pas',
  Horse.Core.Param.Field.Brackets in 'Vendor\Horse\Horse.Core.Param.Field.Brackets.pas',
  Horse.Core.Param.Field in 'Vendor\Horse\Horse.Core.Param.Field.pas',
  Horse.Core.Param.Header in 'Vendor\Horse\Horse.Core.Param.Header.pas',
  Horse.Core.Param in 'Vendor\Horse\Horse.Core.Param.pas',
  Horse.Core in 'Vendor\Horse\Horse.Core.pas',
  Horse.Core.Route.Contract in 'Vendor\Horse\Horse.Core.Route.Contract.pas',
  Horse.Core.Route in 'Vendor\Horse\Horse.Core.Route.pas',
  Horse.Core.RouterTree.NextCaller in 'Vendor\Horse\Horse.Core.RouterTree.NextCaller.pas',
  Horse.Core.RouterTree in 'Vendor\Horse\Horse.Core.RouterTree.pas',
  Horse.Exception.Interrupted in 'Vendor\Horse\Horse.Exception.Interrupted.pas',
  Horse.Exception in 'Vendor\Horse\Horse.Exception.pas',
  Horse.Mime in 'Vendor\Horse\Horse.Mime.pas',
  Horse in 'Vendor\Horse\Horse.pas',
  Horse.Proc in 'Vendor\Horse\Horse.Proc.pas',
  Horse.Provider.Abstract in 'Vendor\Horse\Horse.Provider.Abstract.pas',
  Horse.Provider.Apache in 'Vendor\Horse\Horse.Provider.Apache.pas',
  Horse.Provider.CGI in 'Vendor\Horse\Horse.Provider.CGI.pas',
  Horse.Provider.Console in 'Vendor\Horse\Horse.Provider.Console.pas',
  Horse.Provider.Daemon in 'Vendor\Horse\Horse.Provider.Daemon.pas',
  Horse.Provider.FPC.Apache in 'Vendor\Horse\Horse.Provider.FPC.Apache.pas',
  Horse.Provider.FPC.CGI in 'Vendor\Horse\Horse.Provider.FPC.CGI.pas',
  Horse.Provider.FPC.Daemon in 'Vendor\Horse\Horse.Provider.FPC.Daemon.pas',
  Horse.Provider.FPC.FastCGI in 'Vendor\Horse\Horse.Provider.FPC.FastCGI.pas',
  Horse.Provider.FPC.HTTPApplication in 'Vendor\Horse\Horse.Provider.FPC.HTTPApplication.pas',
  Horse.Provider.FPC.LCL in 'Vendor\Horse\Horse.Provider.FPC.LCL.pas',
  Horse.Provider.IOHandleSSL.Contract in 'Vendor\Horse\Horse.Provider.IOHandleSSL.Contract.pas',
  Horse.Provider.IOHandleSSL in 'Vendor\Horse\Horse.Provider.IOHandleSSL.pas',
  Horse.Provider.ISAPI in 'Vendor\Horse\Horse.Provider.ISAPI.pas',
  Horse.Provider.VCL in 'Vendor\Horse\Horse.Provider.VCL.pas',
  Horse.Request in 'Vendor\Horse\Horse.Request.pas',
  Horse.Response in 'Vendor\Horse\Horse.Response.pas',
  Horse.Rtti.Helper in 'Vendor\Horse\Horse.Rtti.Helper.pas',
  Horse.Rtti in 'Vendor\Horse\Horse.Rtti.pas',
  Horse.Session in 'Vendor\Horse\Horse.Session.pas',
  Horse.WebModule in 'Vendor\Horse\Horse.WebModule.pas' {HorseWebModule: TWebModule},
  ThirdParty.Posix.Syslog in 'Vendor\Horse\ThirdParty.Posix.Syslog.pas',
  Web.WebConst in 'Vendor\Horse\Web.WebConst.pas',
  uMain in 'uMain.pas',
  Horse.Jhonson in 'Vendor\Horse\Horse.Jhonson.pas',
  uPessoa.Controller in 'Infra\Controller\Pessoa\uPessoa.Controller.pas',
  uPessoa.Store.DTO in 'Application\DTO\Pessoa\uPessoa.Store.DTO.pas',
  uBase.DTO in 'Application\DTO\Shared\uBase.DTO.pas',
  uPessoa.Show.DTO in 'Application\DTO\Pessoa\uPessoa.Show.DTO.pas',
  uPessoa.Show.UseCase.Interfaces in 'Application\UseCase\Pessoa\Interfaces\uPessoa.Show.UseCase.Interfaces.pas',
  uPessoa.Show.UseCase in 'Application\UseCase\Pessoa\uPessoa.Show.UseCase.pas',
  uPessoa.Repository.Interfaces in 'Domain\Repository\Pessoa\uPessoa.Repository.Interfaces.pas',
  uRepository.Factory in 'Infra\Repository\Shared\uRepository.Factory.pas',
  uPessoa in 'Domain\Entity\Pessoa\uPessoa.pas',
  uBase.Entity in 'Domain\Entity\Shared\uBase.Entity.pas',
  uPessoa.Repository in 'Infra\Repository\Pessoa\uPessoa.Repository.pas',
  uZLConnection.Interfaces in 'Vendor\ZLConnection\uZLConnection.Interfaces.pas',
  uZLConnection.Types in 'Vendor\ZLConnection\uZLConnection.Types.pas',
  uZLMemTable.Interfaces in 'Vendor\ZLConnection\uZLMemTable.Interfaces.pas',
  uZLQry.Interfaces in 'Vendor\ZLConnection\uZLQry.Interfaces.pas',
  uZLConnection.FireDAC in 'Vendor\ZLConnection\FireDAC\uZLConnection.FireDAC.pas',
  uZLMemTable.FireDAC in 'Vendor\ZLConnection\FireDAC\uZLMemTable.FireDAC.pas',
  uZLQry.FireDAC in 'Vendor\ZLConnection\FireDAC\uZLQry.FireDAC.pas',
  uZLScript.FireDAC in 'Vendor\ZLConnection\FireDAC\uZLScript.FireDAC.pas',
  uZLScript.Interfaces in 'Vendor\ZLConnection\uZLScript.Interfaces.pas',
  uConnection.Factory in 'Infra\Repository\Shared\uConnection.Factory.pas',
  uRepository.Factory.Interfaces in 'Infra\Repository\Shared\uRepository.Factory.Interfaces.pas',
  FireDAC.Phys.PGDef,
  FireDAC.Stan.Intf,
  FireDAC.Phys,
  FireDAC.Phys.PG,
  uPessoa.StoreAndShow.UseCase.Interfaces in 'Application\UseCase\Pessoa\Interfaces\uPessoa.StoreAndShow.UseCase.Interfaces.pas',
  uPessoa.StoreAndShow.UseCase in 'Application\UseCase\Pessoa\uPessoa.StoreAndShow.UseCase.pas',
  uPessoa.Update.DTO in 'Application\DTO\Pessoa\uPessoa.Update.DTO.pas',
  uPessoa.UpdateAndShow.UseCase.Interfaces in 'Application\UseCase\Pessoa\Interfaces\uPessoa.UpdateAndShow.UseCase.Interfaces.pas',
  uPessoa.UpdateAndShow.UseCase in 'Application\UseCase\Pessoa\uPessoa.UpdateAndShow.UseCase.pas',
  uPessoa.Delete.UseCase.Interfaces in 'Application\UseCase\Pessoa\Interfaces\uPessoa.Delete.UseCase.Interfaces.pas',
  uPessoa.Delete.UseCase in 'Application\UseCase\Pessoa\uPessoa.Delete.UseCase.pas',
  uPessoa.Index.UseCase.Interfaces in 'Application\UseCase\Pessoa\Interfaces\uPessoa.Index.UseCase.Interfaces.pas',
  uPessoa.Index.UseCase in 'Application\UseCase\Pessoa\uPessoa.Index.UseCase.pas',
  uRes in 'Infra\Shared\uRes.pas',
  uApplication.Types in 'Infra\Shared\uApplication.Types.pas',
  uResObject in 'Infra\Shared\uResObject.pas',
  uPessoa.FlNatureza.Types in 'Domain\Entity\Pessoa\uPessoa.FlNatureza.Types.pas',
  uCpfCnpj.ValueObject in 'Domain\Entity\Shared\uCpfCnpj.ValueObject.pas',
  uHlp in 'Infra\Shared\uHlp.pas',
  uValueObject.Exception in 'Domain\Exceptions\uValueObject.Exception.pas',
  uEntityValidation.Exception in 'Domain\Exceptions\uEntityValidation.Exception.pas',
  uPessoa.Mapper in 'Infra\Mapper\Pessoa\uPessoa.Mapper.pas',
  uEndereco in 'Domain\Entity\Pessoa\uEndereco.pas',
  uSmartPointer in 'Vendor\SmartPointer\uSmartPointer.pas',
  uPessoa.StoreBatch.DTO in 'Application\DTO\Pessoa\uPessoa.StoreBatch.DTO.pas',
  uPessoa.StoreBatch.UseCase.Interfaces in 'Application\UseCase\Pessoa\Interfaces\uPessoa.StoreBatch.UseCase.Interfaces.pas',
  uPessoa.StoreBatch.UseCase in 'Application\UseCase\Pessoa\uPessoa.StoreBatch.UseCase.pas',
  uTarefa.Repository.Interfaces in 'Domain\Repository\Tarefa\uTarefa.Repository.Interfaces.pas',
  uTarefa.Repository in 'Infra\Repository\Tarefa\uTarefa.Repository.pas',
  uTarefa in 'Domain\Entity\Tarefa\uTarefa.pas',
  uTarefa.Status.Types in 'Domain\Entity\Tarefa\uTarefa.Status.Types.pas',
  uPessoa.UpdateAddressWithViaCep.UseCase.Interfaces in 'Application\UseCase\Pessoa\Interfaces\uPessoa.UpdateAddressWithViaCep.UseCase.Interfaces.pas',
  uPessoa.UpdateAddressWithViaCep.UseCase in 'Application\UseCase\Pessoa\uPessoa.UpdateAddressWithViaCep.UseCase.pas',
  uSearchZipCode.Lib in 'Vendor\SearchZipCode\uSearchZipCode.Lib.pas',
  uEnderecoIntegracao in 'Domain\Entity\Pessoa\uEnderecoIntegracao.pas';

begin
  TMain.Start;
end.
